org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
chenille_version=0.18.0

mod_version=2.0.2
maven_group=net.ntrdeal.echoedremnants

#compile mods:
fabric_api_version=0.160.5+26.3
realapi_version=0.4.94
cca_version=8.0.1

#runtime mods:
modmenu_version=lcxkZSq6
carpet_version=bGrLxJ8v
spark_version=iYFOl6lQ
sodium_version=bAZQdGpg
jei_version=qaCQ7LGO